<a href="https://colab.research.google.com/github/Isaivargas/machineLearningAgents/blob/master/frozenLake/frozenLakeQlearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**The goal of this game is to go from the starting state (S) to the goal state (G) by walking only on frozen tiles (F) and avoid holes (H).However, the ice is slippery, so you won't always move in the direction you intend (stochastic environment).**





> SFFF       (S: starting point, safe) 


> FHFH       (F: frozen surface, safe)


> FFFH       (H: hole, fall to your doom)



> FFFH       (H: hole, fall to your doom)


> HFFG       (G: goal, where the frisbee is located)










In [0]:
import numpy as np
import gym
import random

The Environment is the Frozen Lake from **Open AI **


In [0]:
env = gym.make("FrozenLake-v0") #This environment produce a 4x4 tiles.
#env = gym.make("FrozenLake-v0", desc=None, map_name=None) #This environmnet produce a 8 x 8 tiles
#env.reset()  # Returns an initial observation.
#env.render() # Render the environment at initial state that is the same as the first observation.

Step #1 
Creation of Q Table and initialization.



In [0]:
action_size = env.action_space.n
state_size  = env.observation_space.n

In [113]:
# Nrows (states) & Mcolumns(actions).
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Create the hyperparameters.

In [0]:
total_episodes   = 15000        # Total episodes
learning_rate    = 0.6          # Learning rate (How much you accept the new value vs the old value).
max_steps        = 99           # Max steps per episode
gamma            = 0.99         # Discounting rate

# Exploration parameters
epsilon          = 1.0          # Exploration rate # Set the percent the Agent gonna explore.
max_epsilon      = 1.0          # Exploration probability at start
min_epsilon      = 0.01         # Minimum exploration probability 
decay_rate       = 0.001        # Exponential decay rate for exploration prob

The Q learning algorithm 🧠
implementation of the Q learning algorithm


In [115]:
# List of rewards
rewards = []

# Step 2 For life or until learning is stopped.
# Loop of episodes (Trajectories).
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0

    # Loop of steps.
    for step in range(max_steps):
        # Step 3. Choose an action a in the current world state (s)
        ## Generate a random number.
        exp_exp_tradeoff = random.uniform(0, 1)
        
        ## If this number > greater than epsilon --> Produce an exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> Produce an exploration.
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        #Learning Process 
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        
        total_rewards += reward
        
        # Our new state is state
        state = new_state
        
        # If done (if we're dead) : finish episode
        if done == True: 
            break
        
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode) 
    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.4112
[[3.83682771e-01 1.43476236e-01 7.37654001e-02 7.52308320e-02]
 [7.72831109e-03 2.32112131e-02 1.65793581e-02 1.16574006e-01]
 [2.50754371e-02 2.05284469e-01 2.04893875e-02 4.95190490e-02]
 [1.71085464e-02 4.39673930e-02 3.43890396e-02 9.48461806e-02]
 [4.28220293e-01 8.37185799e-02 2.01327089e-02 2.60791483e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.04971005e-03 4.91770654e-05 8.89437502e-02 1.39272241e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [9.75213229e-02 1.40081726e-01 7.22546839e-02 5.52897664e-01]
 [1.33976449e-02 4.06296906e-01 8.46134296e-02 1.08837124e-01]
 [6.65461974e-01 2.36130237e-03 2.56463682e-02 6.69168823e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.05464650e-02 1.49076653e-01 7.83556940e-01 1.46811007e-01]
 [4.07139584e-01 9.16606408e-01 2.40297225e-01 6.23947685e-01]
 [0.00000000e+00 0.00000000e+00

In [127]:
env.reset()

for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):

        #env.render() # Render the state of the agent while is playing uncoment to watch it .

        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])
        
        new_state, reward, done, info = env.step(action)
        
        

        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()

            # Here we check if the reward is equal to 1 the agent achieve the goal else fell into a hole.
            if reward == 1: 
              print("Goal reached 🏆")
            else:
              print("Fell into a hole ☠️")
            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Right)
SFFF
FHFH
FFFH
HFFG
Fell into a hole ☠️
Number of steps 22
****************************************************
EPISODE  1
  (Right)
SFFF
FHFH
FFFH
HFFG
Fell into a hole ☠️
Number of steps 27
****************************************************
EPISODE  2
  (Down)
SFFF
FHFH
FFFH
HFFG
Goal reached 🏆
Number of steps 16
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Goal reached 🏆
Number of steps 87
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Goal reached 🏆
Number of steps 39
